env:
  cuda: True
  seed: 42

data_loader:
  train_validation_split: 8/9
  bucket_seqs: True
  batch_size: 64
  num_workers: 0

model:
  embedding_dim: 64
  hidden_size: 128
  rnn: 'GRU'
  dropout: 0.0
  basis_type: 'dyadic'
  basis_means:
    - 0
    - 1
    - 2
    - 4
    - 6
    - 8
    - 12
    - 25
    - 52

train:
  optimizer: 'Adam'
  lr: 0.001
  epochs: 150
  l2_reg: 0
  steps: 50
  attr_batch_size: 8
  occurred_type_only: True
  tune_metric: 'nll'

predict:
  min_days: 1
  max_days: 30
