env:
  cuda: True
  seed: 42

preprocessing:
  seed: 42
  sampling:
    max_positives: 6000  # This results in a maximum sample size of 102,000 accounts
    neg_w_activity_prop: 8
    neg_w_intent_prop: 4
    neg_w_none_prop: 4
  firmo_rollup:
    top_n_categories: 5
  activity_rollup:
    min_occurrences: 150
    min_accounts: 75
  train_size: 0.8

data_loader:
  train_validation_split: 0.85
  bucket_seqs: True
  batch_size: 64
  num_workers: 0

model:
  embedding_dim: 64
  hidden_size: 128
  rnn: 'GRU'
  dropout: 0.0
  basis_type: 'means'
  basis_means:
    - 0
    - 1
    - 2
    - 4
    - 6
    - 8
    - 12
    - 25
    - 52
  max_log_basis_weight: 10
  ks:
    - 0.001
    - 0.01
    - 0.1
    - 0.5
    - 1.0
    - 2.0

train:
  optimizer: 'Adam'
  lr: 0.001
  epochs: 150
  l2_reg: 0
  steps: 50
  tune_metric: 'nll'
  patience: 3

attribution:
  attr_batch_size: 8
  occurred_type_only: True

predict:
  min_time_steps: 1
  max_time_steps: 5
