COUNTRY_MAP = {
    # country names to 2-digit codes
    "anonymous proxies": "A1",
    "satellite providers": "A2",
    "andorra": "AD",
    "united arab emirates": "AE",
    "afghanistan": "AF",
    "antigua and barbuda": "AG",
    "anguilla": "AI",
    "albania": "AL",
    "armenia": "AM",
    "netherlands antilles": "AN",
    "angola": "AO",
    "asia pacific region": "AP",
    "antarctica": "AQ",
    "argentina": "AR",
    "american samoa": "AS",
    "austria": "AT",
    "australia": "AU",
    "aruba": "AW",
    "aland islands": "AX",
    "åland islands": "AX",
    "azerbaijan": "AZ",
    "bosnia and herzegovina": "BA",
    "bosnia and herzegowina": "BA",
    "bosnia": "BA",
    "barbados": "BB",
    "bangladesh": "BD",
    "belgium": "BE",
    "burkina faso": "BF",
    "bulgaria": "BG",
    "bahrain": "BH",
    "burundi": "BI",
    "benin": "BJ",
    "saint barthélemy": "BL",
    "saint barthelemy": "BL",
    "bermuda": "BM",
    "brunei darussalam": "BN",
    "brunei": "BN",
    "bolivia": "BO",
    "bolivia plurinational state of": "BO",
    "bonaire saint eustatius and saba": "BQ",
    "bonaire sint eustatius and saba": "BQ",
    "brazil": "BR",
    "bahamas": "BS",
    "bhutan": "BT",
    "bouvet island": "BV",
    "botswana": "BW",
    "belarus": "BY",
    "belize": "BZ",
    "canada": "CA",
    "cocos (keeling) islands": "CC",
    "cocos keeling islands": "CC",
    "cocos islands": "CC",
    "congo the democratic republic of the": "CD",
    "democratic republic of the congo": "CD",
    "democratic republic of congo": "CD",
    "central african republic": "CF",
    "congo": "CG",
    "republic of the congo": "CG",
    "republic of congo": "CG",
    "switzerland": "CH",
    "côte d'ivoire": "CI",
    "cote d'ivoire": "CI",
    "ivory coast": "CI",
    "cook islands": "CK",
    "chile": "CL",
    "cameroon": "CM",
    "china": "CN",
    "colombia": "CO",
    "costa rica": "CR",
    "cuba": "CU",
    "cape verde": "CV",
    "curaçao": "CW",
    "curacao": "CW",
    "christmas island": "CX",
    "cyprus": "CY",
    "czech republic": "CZ",
    "germany": "DE",
    "djibouti": "DJ",
    "denmark": "DK",
    "dominica": "DM",
    "dominican republic": "DO",
    "república dominicana": "DO",
    "republica dominicana": "DO",
    "algeria": "DZ",
    "ecuador": "EC",
    "estonia": "EE",
    "egypt": "EG",
    "western sahara": "EH",
    "eritrea": "ER",
    "spain": "ES",
    "ethiopia": "ET",
    "europe": "EU",
    "finland": "FI",
    "fiji": "FJ",
    "fiji islands": "FJ",
    "falkland islands (malvinas)": "FK",
    "falkland (malvinas) islands": "FK",
    "falkland islands": "FK",
    "micronesia federated states of": "FM",
    "micronesia": "FM",
    "faroe islands": "FO",
    "faeroe islands": "FO",
    "france": "FR",
    "gabon": "GA",
    "united kingdom": "GB",
    "grenada": "GD",
    "georgia": "GE",
    "french guiana": "GF",
    "guernsey": "GG",
    "ghana": "GH",
    "gibraltar": "GI",
    "greenland": "GL",
    "gambia": "GM",
    "guinea": "GN",
    "guadeloupe": "GP",
    "equatorial guinea": "GQ",
    "greece": "GR",
    "south georgia and the south sandwich islands": "GS",
    "guatemala": "GT",
    "guam": "GU",
    "guinea-bissau": "GW",
    "guyana": "GY",
    "hong kong": "HK",
    "heard island and mcdonald islands": "HM",
    "honduras": "HN",
    "croatia": "HR",
    "haiti": "HT",
    "hungary": "HU",
    "indonesia": "ID",
    "ireland": "IE",
    "israel": "IL",
    "isle of man": "IM",
    "india": "IN",
    "british indian ocean territory": "IO",
    "iraq": "IQ",
    "iran": "IR",
    "iran islamic republic of": "IR",
    "iceland": "IS",
    "italy": "IT",
    "jersey": "JE",
    "jamaica": "JM",
    "jordan": "JO",
    "japan": "JP",
    "kenya": "KE",
    "kyrgyzstan": "KG",
    "cambodia": "KH",
    "kiribati": "KI",
    "comoros": "KM",
    "saint kitts and nevis": "KN",
    "korea democratic people's republic of": "KP",
    "north korea": "KP",
    "korea republic of": "KR",
    "south korea": "KR",
    "kuwait": "KW",
    "cayman islands": "KY",
    "kazakhstan": "KZ",
    "lao people's democratic republic": "LA",
    "laos": "LA",
    "lebanon": "LB",
    "saint lucia": "LC",
    "liechtenstein": "LI",
    "sri lanka": "LK",
    "liberia": "LR",
    "lesotho": "LS",
    "lithuania": "LT",
    "luxembourg": "LU",
    "latvia": "LV",
    "libya": "LY",
    "morocco": "MA",
    "monaco": "MC",
    "moldova republic of": "MD",
    "moldova": "MD",
    "montenegro": "ME",
    "saint martin (french part)": "MF",
    "saint martin": "MF",
    "madagascar": "MG",
    "marshall islands": "MH",
    "macedonia the former yugoslav republic of": "MK",
    "macedonia": "MK",
    "mali": "ML",
    "myanmar": "MM",
    "mongolia": "MN",
    "macao": "MO",
    "macau": "MO",
    "northern mariana islands": "MP",
    "martinique": "MQ",
    "mauritania": "MR",
    "montserrat": "MS",
    "malta": "MT",
    "mauritius": "MU",
    "maldives": "MV",
    "maldives islands": "MV",
    "malawi": "MW",
    "mexico": "MX",
    "méxico": "MX",
    "malaysia": "MY",
    "mozambique": "MZ",
    "namibia": "NA",
    "new caledonia": "NC",
    "niger": "NE",
    "norfolk island": "NF",
    "nigeria": "NG",
    "nicaragua": "NI",
    "netherlands": "NL",
    "the netherlands": "NL",
    "holland": "NL",
    "norway": "NO",
    "nepal": "NP",
    "nauru": "NR",
    "niue": "NU",
    "new zealand": "NZ",
    "other country": "O1",
    "oman": "OM",
    "sultanate of oman": "OM",
    "panama": "PA",
    "peru": "PE",
    "french polynesia": "PF",
    "papua new guinea": "PG",
    "philippines": "PH",
    "pakistan": "PK",
    "poland": "PL",
    "saint pierre and miquelon": "PM",
    "pitcairn": "PN",
    "puerto rico": "PR",
    "palestine": "PS",
    "palestinian territory": "PS",
    "palestine state of": "PS",
    "portugal": "PT",
    "palau": "PW",
    "paraguay": "PY",
    "qatar": "QA",
    "réunion": "RE",
    "reunion": "RE",
    "romania": "RO",
    "serbia": "RS",
    "russia": "RU",
    "russian federation": "RU",
    "rwanda": "RW",
    "saudi arabia": "SA",
    "kingdom of saudi arabia": "SA",
    "solomon islands": "SB",
    "seychelles": "SC",
    "sudan": "SD",
    "sweden": "SE",
    "singapore": "SG",
    "saint helena": "SH",
    "saint helena ascension and tristan da cunha": "SH",
    "slovenia": "SI",
    "svalbard and jan mayen": "SJ",
    "slovakia": "SK",
    "sierra leone": "SL",
    "san marino": "SM",
    "senegal": "SN",
    "somalia": "SO",
    "suriname": "SR",
    "south sudan": "SS",
    "são tomé and príncipe": "ST",
    "sao tome and principe": "ST",
    "são tomé": "ST",
    "sao tome": "ST",
    "el salvador": "SV",
    "sint maarten (dutch part)": "SX",
    "sint maarten": "SX",
    "syrian arab republic": "SY",
    "syria": "SY",
    "swaziland": "SZ",
    "turks and caicos islands": "TC",
    "turks caicos": "TC",
    "chad": "TD",
    "french southern territories": "TF",
    "togo": "TG",
    "thailand": "TH",
    "tajikistan": "TJ",
    "tokelau": "TK",
    "timor-leste": "TL",
    "east timor": "TL",
    "turkmenistan": "TM",
    "tunisia": "TN",
    "tonga": "TO",
    "turkey": "TR",
    "trinidad and tobago": "TT",
    "tuvalu": "TV",
    "taiwan": "TW",
    "taiwan province of china": "TW",
    "taiwan roc": "TW",
    "tanzania united republic of": "TZ",
    "tanzania": "TZ",
    "ukraine": "UA",
    "uganda": "UG",
    "united states minor outlying islands": "UM",
    "united states of america": "US",
    "united states": "US",
    "uruguay": "UY",
    "uzbekistan": "UZ",
    "holy see (vatican city state)": "VA",
    "vatican city": "VA",
    "vatican": "VA",
    "saint vincent and the grenadines": "VC",
    "venezuela": "VE",
    "venezuela bolivarian republic of": "VE",
    "virgin islands british": "VG",
    "british virgin islands": "VG",
    "virgin islands us": "VI",
    "us virgin islands": "VI",
    "viet nam": "VN",
    "vietnam": "VN",
    "vanuatu": "VU",
    "wallis and futuna": "WF",
    "samoa": "WS",
    "kosovo": "XK",
    "yemen": "YE",
    "mayotte": "YT",
    "south africa": "ZA",
    "zambia": "ZM",
    "zimbabwe": "ZW",

    # 3-digit codes to 2-digit codes
    "and": "AD",
    "are": "AE",
    "uae": "AE",
    "afg": "AF",
    "atg": "AG",
    "aia": "AI",
    "alb": "AL",
    "arm": "AM",
    "ago": "AO",
    "ata": "AQ",
    "arg": "AR",
    "asm": "AS",
    "aut": "AT",
    "aus": "AU",
    "abw": "AW",
    "ala": "AX",
    "aze": "AZ",
    "bih": "BA",
    "brb": "BB",
    "bgd": "BD",
    "bel": "BE",
    "bfa": "BF",
    "bgr": "BG",
    "bhr": "BH",
    "bdi": "BI",
    "ben": "BJ",
    "blm": "BL",
    "bmu": "BM",
    "brn": "BN",
    "bol": "BO",
    "bes": "BQ",
    "bra": "BR",
    "bah": "BS",
    "bhs": "BS",
    "btn": "BT",
    "bvt": "BV",
    "bwa": "BW",
    "blr": "BY",
    "blz": "BZ",
    "can": "CA",
    "cck": "CC",
    "cod": "CD",
    "caf": "CF",
    "cog": "CG",
    "che": "CH",
    "civ": "CI",
    "cok": "CK",
    "chl": "CL",
    "cmr": "CM",
    "chn": "CN",
    "col": "CO",
    "cri": "CR",
    "cub": "CU",
    "cpv": "CV",
    "cuw": "CW",
    "cxr": "CX",
    "cyp": "CY",
    "cze": "CZ",
    "deu": "DE",
    "dji": "DJ",
    "dnk": "DK",
    "dma": "DM",
    "dom": "DO",
    "dza": "DZ",
    "ecu": "EC",
    "est": "EE",
    "egy": "EG",
    "esh": "EH",
    "eri": "ER",
    "esp": "ES",
    "eth": "ET",
    "fin": "FI",
    "fji": "FJ",
    "flk": "FK",
    "fsm": "FM",
    "fro": "FO",
    "fra": "FR",
    "gab": "GA",
    "gbr": "GB",
    "grd": "GD",
    "geo": "GE",
    "guf": "GF",
    "ggy": "GG",
    "gha": "GH",
    "gib": "GI",
    "grl": "GL",
    "gmb": "GM",
    "gin": "GN",
    "glp": "GP",
    "gnq": "GQ",
    "grc": "GR",
    "sgs": "GS",
    "gtm": "GT",
    "gum": "GU",
    "gnb": "GW",
    "guy": "GY",
    "hkg": "HK",
    "hmd": "HM",
    "hnd": "HN",
    "hrv": "HR",
    "hti": "HT",
    "hun": "HU",
    "idn": "ID",
    "irl": "IE",
    "isr": "IL",
    "imn": "IM",
    "ind": "IN",
    "iot": "IO",
    "irq": "IQ",
    "irn": "IR",
    "isl": "IS",
    "ita": "IT",
    "jey": "JE",
    "jam": "JM",
    "jor": "JO",
    "jpn": "JP",
    "ken": "KE",
    "kgz": "KG",
    "khm": "KH",
    "kir": "KI",
    "com": "KM",
    "kna": "KN",
    "prk": "KP",
    "kor": "KR",
    "kwt": "KW",
    "cym": "KY",
    "kaz": "KZ",
    "lao": "LA",
    "lbn": "LB",
    "lca": "LC",
    "lie": "LI",
    "lka": "LK",
    "lbr": "LR",
    "lso": "LS",
    "ltu": "LT",
    "lux": "LU",
    "lva": "LV",
    "lby": "LY",
    "mar": "MA",
    "mco": "MC",
    "mda": "MD",
    "mne": "ME",
    "maf": "MF",
    "mdg": "MG",
    "mhl": "MH",
    "mkd": "MK",
    "mli": "ML",
    "mmr": "MM",
    "mng": "MN",
    "mac": "MO",
    "mnp": "MP",
    "mtq": "MQ",
    "mrt": "MR",
    "msr": "MS",
    "mlt": "MT",
    "mus": "MU",
    "mdv": "MV",
    "mwi": "MW",
    "mex": "MX",
    "mys": "MY",
    "moz": "MZ",
    "nam": "NA",
    "ncl": "NC",
    "ner": "NE",
    "nfk": "NF",
    "nga": "NG",
    "nic": "NI",
    "nld": "NL",
    "nor": "NO",
    "npl": "NP",
    "nru": "NR",
    "niu": "NU",
    "nzl": "NZ",
    "omn": "OM",
    "pan": "PA",
    "per": "PE",
    "pyf": "PF",
    "png": "PG",
    "phl": "PH",
    "pak": "PK",
    "pol": "PL",
    "spm": "PM",
    "pcn": "PN",
    "pri": "PR",
    "pse": "PS",
    "prt": "PT",
    "plw": "PW",
    "pry": "PY",
    "qat": "QA",
    "reu": "RE",
    "rom": "RO",
    "srb": "RS",
    "rus": "RU",
    "rwa": "RW",
    "sau": "SA",
    "ksa": "SA",
    "slb": "SB",
    "syc": "SC",
    "sdn": "SD",
    "swe": "SE",
    "sgp": "SG",
    "shn": "SH",
    "svn": "SI",
    "sjm": "SJ",
    "svk": "SK",
    "sle": "SL",
    "smr": "SM",
    "sen": "SN",
    "som": "SO",
    "sur": "SR",
    "ssd": "SS",
    "stp": "ST",
    "slv": "SV",
    "sxm": "SX",
    "syr": "SY",
    "swz": "SZ",
    "tca": "TC",
    "tcd": "TD",
    "atf": "TF",
    "tgo": "TG",
    "tha": "TH",
    "tjk": "TJ",
    "tkl": "TK",
    "tls": "TL",
    "tkm": "TM",
    "tun": "TN",
    "tom": "TO",
    "tur": "TR",
    "tto": "TT",
    "tuv": "TV",
    "twn": "TW",
    "tza": "TZ",
    "ukr": "UA",
    "uga": "UG",
    "umi": "UM",
    "usa": "US",
    "ury": "UY",
    "uzb": "UZ",
    "vat": "VA",
    "vct": "VT",
    "ven": "VE",
    "vgb": "VG",
    "vir": "VI",
    "vnm": "VN",
    "vut": "VU",
    "wlf": "WF",
    "wsm": "WS",
    "yem": "YE",
    "myt": "YT",
    "rsa": "ZA",
    "zaf": "ZA",
    "zmb": "ZM",
    "zwe": "ZW",
}
